### ISSUE TITLE
auto install script fails

### ISSUE THREAD

**Issue by chiwalfrm** [bismuthfoundation/hypernode#5]
on a freshly installed Ubuntu 18.04.3 LTS desktop system with only the latest updates plus 'curl' installed.

Logfile: https://drive.google.com/file/d/1bjo0usmSuBbED-076rvVOLiG-of0tXWd/view?usp=sharing

the last part of the log has errors:
```
Checking Hypernode
Traceback (most recent call last):
  File "hn_check.py", line 26, in <module>
    import poshn
  File "../modules/poshn.py", line 47, in <module>
    import com_helpers
  File "../modules/com_helpers.py", line 12, in <module>
    import commands_pb2
  File "../modules/commands_pb2.py", line 143, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "hn_check.py", line 26, in <module>
    import poshn
  File "../modules/poshn.py", line 47, in <module>
    import com_helpers
  File "../modules/com_helpers.py", line 12, in <module>
    import commands_pb2
  File "../modules/commands_pb2.py", line 143, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
no crontab for root
no crontab for root
Rebooting server.
```

**Comment by EggPool** [comment]
Probably desktop Ubuntu has some packages missing from server version (18.04 server is the reference install).

Can you  
`cd /root/hypernode/main`  
`python3.7 hn_check.py`

and report?  
Would be easier if you came on the discord for faster feedback  
https://discord.gg/G5gUbkn

**Comment by chiwalfrm** [comment]
I will try again with Server ISO.  But below is the logfile from the Desktop.

```
root@vmware-virtual-machine:~/hypernode/main# python3.7 hn_check.py
Traceback (most recent call last):
  File "hn_check.py", line 26, in <module>
    import poshn
  File "../modules/poshn.py", line 47, in <module>
    import com_helpers
  File "../modules/com_helpers.py", line 12, in <module>
    import commands_pb2
  File "../modules/commands_pb2.py", line 143, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
 
Original exception was:
Traceback (most recent call last):
  File "hn_check.py", line 26, in <module>
    import poshn
  File "../modules/poshn.py", line 47, in <module>
    import com_helpers
  File "../modules/com_helpers.py", line 12, in <module>
    import commands_pb2
  File "../modules/commands_pb2.py", line 143, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
root@vmware-virtual-machine:~/hypernode/main#
```

**Comment by EggPool** [comment]
Ok, looks like an old protobuf module.

Can you run 
`python3.7 -m pip freeze | grep proto`
And report your version?

I do have 
protobuf==3.9.0
or
protobuff==3.6.1
depending on the setups.

Likely you have an older one. (more concerning if newer)

**Comment by chiwalfrm** [comment]
I installed again with the Server ISO and it worked perfectly.  You can close this issue (I don't have the Desktop install any more to test further).

**Comment by EggPool** [comment]
Thanks!

**Comment by hclivess** [comment]
Just encountered this, 

`python3.7 -m pip install protobuf --upgrade
`

fixes this, could be added to the install script
